//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clientdbEntities : DbContext
    {
        public clientdbEntities()
            : base("name=clientdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<contactholder> contactholder { get; set; }
        public virtual DbSet<privacylvl> privacylvl { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<company_contact> company_contact { get; set; }
        public virtual DbSet<company_user1> company_user1Set { get; set; }
    }
}
