//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_user1
    {
        public int company_userId { get; set; }
        public int cucompanyId { get; set; }
        public int cuuserID { get; set; }
    
        public virtual company company { get; set; }
        public virtual user user { get; set; }
    }
}
