//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.company_user = new HashSet<company_user1>();
            this.company_contact1 = new HashSet<company_contact>();
        }
    
        public int companyId { get; set; }
        public string companyName { get; set; }
        public int cdepartmentId { get; set; }
        public Nullable<int> companyCode { get; set; }
        public string companyHead { get; set; }
        public Nullable<System.DateTime> companyDate { get; set; }
        public string companyComment { get; set; }
        public string companyPayment { get; set; }
        public int companyEdition { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<company_user1> company_user { get; set; }
        public virtual ICollection<company_contact> company_contact1 { get; set; }
    }
}
