//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_contact
    {
        public int company_contactId { get; set; }
        public int ccContactId { get; set; }
        public int ccCompanyId { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual company company1 { get; set; }
    }
}
