//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.company_contact = new HashSet<company_contact>();
        }
    
        public int contactId { get; set; }
        public string contact1 { get; set; }
        public int holderId { get; set; }
        public int contactType { get; set; }
    
        public virtual contactholder contactholder { get; set; }
        public virtual ICollection<company_contact> company_contact { get; set; }
    }
}
