//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactholder
    {
        public contactholder()
        {
            this.contact = new HashSet<contact>();
        }
    
        public int contactHolderId { get; set; }
        public string name { get; set; }
        public sbyte level { get; set; }
    
        public virtual ICollection<contact> contact { get; set; }
    }
}
