//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.company = new HashSet<company>();
        }
    
        public int departmentId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<company> company { get; set; }
    }
}
