//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class privacylvl
    {
        public privacylvl()
        {
            this.user = new HashSet<user>();
        }
    
        public int privacyLvlId { get; set; }
        public short groupNumber { get; set; }
        public short persInfo { get; set; }
        public short redact { get; set; }
        public short letter { get; set; }
        public short agreement { get; set; }
        public short layout { get; set; }
        public short payment { get; set; }
        public short act { get; set; }
        public short columnName { get; set; }
        public short columnDepartment { get; set; }
        public short columnCode { get; set; }
        public short columnFullName { get; set; }
        public short columnContacts { get; set; }
        public short columnState { get; set; }
    
        public virtual ICollection<user> user { get; set; }
    }
}
