//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessToClientsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.company_user = new HashSet<company_user1>();
        }
    
        public int userId { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string surname { get; set; }
        public int accessLvl { get; set; }
        public Nullable<int> group { get; set; }
    
        public virtual privacylvl privacylvl { get; set; }
        public virtual ICollection<company_user1> company_user { get; set; }
    }
}
